baseURL = "https://jeuxvideofrancais.mokay.fr/"
title = "Jeux vidéo en français"
theme = "jvfr"

enableRobotsTXT = true
languageCode = "fr"
defaultContentLanguage = "fr"

disqusShortname = "jeuxvideofrancais"

[params]
logo = "img/logo128.png"
logoFull = "img/logo.png"
logoSquare = "img/logo-square.png"
description = "Jeux vidéo en français est un site proposant des traductions de jaquettes de jeux vidéo dans la langue française."
author = "palisir"

[blackfriday]
  hrefTargetBlank = true
